### ISSUE TITLE
about your username

### ISSUE THREAD

**Issue by Kivylius** [webfront/learning_nodejs#1]
Dear sir or Madam,
I have no way to contract you other then to create this issue. I run a small company called http://webfront.ie and would we are creating a few libraries open source, this username would fit our company quite well, if you could please give us this username, we would be grateful and definitely include you in the hall of fame! if you want to talk further, contact me at cezar at webfront.ie. Thank you very much!.

**Comment by Kivylius** [comment]
@webfront ?

**Comment by webfront** [comment]
Hi, I used to have a small company called Webfront Software Solutions. I don't mind if you take my username but not too sure how I have to do it. Apologies for the delay in response.

**Comment by Kivylius** [comment]
hi, thanks for the reply, glad to hear back from you. As GitHub recommends is to rename your username in profile settings and ill be able to take it. let me know, thanks. :)

**Comment by Kivylius** [comment]
@webfront ?

**Comment by Kivylius** [comment]
would you be able to do this? i would really appreciate it, thanks.

**Comment by Kivylius** [comment]
hi, can you please release this username if you are not using it? please.
